package com.orm;
// default package
// Generated 2015-5-21 22:24:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "GOODS", schema = "ANYUE")
public class Goods implements java.io.Serializable {

	private Integer id;
	private String goodsname;
	private Integer goodsnum;
	private Date goodsmaketime;//生产日期
	private Date usefultime;//有效期
	private byte[] goodscard;//合格证
	private InGoods ingoods;
	
	public Goods() {
	}

	public Goods(Integer id) {
		this.id = id;
	}

	public Goods(Integer id, String goodsname, Integer goodsnum,
			Date goodsmaketime, Date usefultime, byte[] goodscard,
			InGoods ingoods) {
		super();
		this.id = id;
		this.goodsname = goodsname;
		this.goodsnum = goodsnum;
		this.goodsmaketime = goodsmaketime;
		this.usefultime = usefultime;
		this.goodscard = goodscard;
		this.ingoods = ingoods;
	}

	@Id
	@SequenceGenerator(name="sequenceGoods",sequenceName="SEQ")
	@GeneratedValue(generator="sequenceGoods",strategy=GenerationType.SEQUENCE)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "GOODSNAME", length = 30)
	public String getGoodsname() {
		return goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	@Column(name = "GOODSNUM", precision = 22, scale = 0)
	public Integer getGoodsnum() {
		return goodsnum;
	}

	public void setGoodsnum(Integer goodsnum) {
		this.goodsnum = goodsnum;
	}

	public Date getGoodsmaketime() {
		return goodsmaketime;
	}

	public void setGoodsmaketime(Date goodsmaketime) {
		this.goodsmaketime = goodsmaketime;
	}

	public Date getUsefultime() {
		return usefultime;
	}

	public void setUsefultime(Date usefultime) {
		this.usefultime = usefultime;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "GOODSCARD", columnDefinition = "BLOB",nullable=true)
	public byte[] getGoodscard() {
		return goodscard;
	}

	public void setGoodscard(byte[] goodscard) {
		this.goodscard = goodscard;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INGOODSID")
	public InGoods getIngoods() {
		return ingoods;
	}

	public void setIngoods(InGoods ingoods) {
		this.ingoods = ingoods;
	}

}
