package com.orm;
// default package
// Generated 2015-5-21 22:24:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "LICENCE", schema = "ANYUE")
public class Licence implements java.io.Serializable {

	private Integer id;//许可证id
	private String orgcode;//许可证的单位
	private String orgname;//许可证单位名称
	private Date starttime;//有效期
	private Date endtime;
	private String licencestatus;//许可证是否有效
	private String filetype;
	private byte[] licence;//许可证
	
	public Licence() {
	}

	public Licence(Integer id) {
		this.id = id;
	}



	public Licence(Integer id, String orgcode, String orgname, Date starttime,
			Date endtime, String licencestatus, String filetype, byte[] licence) {
		super();
		this.id = id;
		this.orgcode = orgcode;
		this.orgname = orgname;
		this.starttime = starttime;
		this.endtime = endtime;
		this.licencestatus = licencestatus;
		this.filetype=filetype;
		this.licence = licence;
	}

	@Id
	@SequenceGenerator(name="sequenceLicence",sequenceName="SEQ")
	@GeneratedValue(generator="sequenceLicence",strategy=GenerationType.SEQUENCE)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ORGCODE", length = 30)
	public String getOrgcode() {
		return orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	@Column(name = "ORGNAME", length = 50)
	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Date getStarttime() {
		return starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "LICENCESTATUS", length = 10)
	public String getLicencestatus() {
		return licencestatus;
	}

	public void setLicencestatus(String licencestatus) {
		this.licencestatus = licencestatus;
	}
	
	@Column(name = "FILETYPE", length = 10)
	public String getFiletype() {
		return filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "LICENCE", columnDefinition = "BLOB",nullable=true)
	public byte[] getLicence() {
		return licence;
	}

	public void setLicence(byte[] licence) {
		this.licence = licence;
	}

}
