package com.orm;
// default package
// Generated 2015-5-21 22:24:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "NOTICE", schema = "ANYUE")
public class Notice implements java.io.Serializable {

	private Integer id;//公告id
	private String tittle;//公告标题
	private String publisherid;//发布公告通知新闻宣传的用户id
	private String publishername;
	private Date publishtime;//通知发布时间
	private byte[] content;//内容
	private String text;//内容
	
	public Notice() {
	}

	public Notice(Integer id) {
		this.id = id;
	}



	public Notice(Integer id, String tittle, String publisherid,
			String publishername, Date publishtime, byte[] content) {
		super();
		this.id = id;
		this.tittle = tittle;
		this.publisherid = publisherid;
		this.publishername = publishername;
		this.publishtime = publishtime;
		this.content = content;
	}

	@Id
	@SequenceGenerator(name="sequenceNotice",sequenceName="SEQ")
	@GeneratedValue(generator="sequenceNotice",strategy=GenerationType.SEQUENCE)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TITTLE", length = 50)
	public String getTittle() {
		return tittle;
	}

	public void setTittle(String tittle) {
		this.tittle = tittle;
	}

	@Column(name = "PUBLISHERID", length = 20)
	public String getPublisherid() {
		return publisherid;
	}

	public void setPublisherid(String publisherid) {
		this.publisherid = publisherid;
	}

	@Column(name = "PUBLISHERNAME", length = 30)
	public String getPublishername() {
		return publishername;
	}

	public void setPublishername(String publishername) {
		this.publishername = publishername;
	}

	public Date getPublishtime() {
		return publishtime;
	}

	public void setPublishtime(Date publishtime) {
		this.publishtime = publishtime;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "CONTENT", columnDefinition = "BLOB",nullable=true)
	public byte[] getContent() {
		return content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	@Column(name = "TEXT", length = 1000)
	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	
}
