package com.orm;
// default package
// Generated 2015-5-21 22:24:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "ORGANIZE", schema = "ANYUE")
public class Organize implements java.io.Serializable {

	private String orgcode;
	private String orgname;
	private String orglocation;
	private String chairman;//负责人
	private Date addtime;//添加创建时间
	private String orgdes;//机构描述
	private String callnum;//电话
	private String email;
	private String parentcode;//分局，分所的上级监管部门
	private String parentname;
	private String belongcode;//餐饮店所属的监管部门编号
	private String belongname;
	private Date runtime;//开业时间
	private String managearea;//监管部门辖区
	private String cateringtype;//餐饮店类型
	private String orgtype;
	private Set<OrgStaff> orgstaff = new HashSet<OrgStaff>(0);//餐饮店员工 
	private Set<TrainContent> traincontents = new HashSet<TrainContent>(0);//培训
	
	public Organize() {
	}
	
	public Organize(String orgcode) {
		super();
		this.orgcode = orgcode;
	}

	public Organize(String orgcode, String orgname, String orglocation,
			String chairman, Date addtime, String orgdes, String callnum, String email,
			String parentcode, String parentname, String belongcode,
			String belongname, Date runtime, String managearea,
			String cateringtype, String orgtype, Set<OrgStaff> orgstaff, Set<TrainContent> traincontents) {
		super();
		this.orgcode = orgcode;
		this.orgname = orgname;
		this.orglocation = orglocation;
		this.chairman = chairman;
		this.addtime = addtime;
		this.orgdes = orgdes;
		this.callnum = callnum;
		this.email = email;
		this.parentcode = parentcode;
		this.parentname = parentname;
		this.belongcode = belongcode;
		this.belongname = belongname;
		this.runtime = runtime;
		this.managearea = managearea;
		this.cateringtype = cateringtype;
		this.orgtype=orgtype;
		this.orgstaff = orgstaff;
		this.traincontents=traincontents;
	}
	
	@ManyToMany(targetEntity=TrainContent.class, cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
	@JoinTable(name = "TRAIN_ORG", schema = "ANYUE", joinColumns = { @JoinColumn(name = "ORGID", nullable=false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "TRAINID", nullable = false, updatable = false) })
	public Set<TrainContent> getTraincontents() {
		return traincontents;
	}

	public void setTraincontents(Set<TrainContent> traincontents) {
		this.traincontents = traincontents;
	}

	@Id
	@Column(name = "ORGCODE", unique = true, nullable = false, length = 30)
	public String getOrgcode() {
		return this.orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}
	
	@Column(name = "ORGNAME", length = 30)
	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	@Column(name = "ORGLOCATION", length = 50)
	public String getOrglocation() {
		return orglocation;
	}

	public void setOrglocation(String orglocation) {
		this.orglocation = orglocation;
	}

	@Column(name = "CHAIRMAN", length = 10)
	public String getChairman() {
		return chairman;
	}

	public void setChairman(String chairman) {
		this.chairman = chairman;
	}

	public Date getAddtime() {
		return addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	@Column(name = "ORGDES", length = 100)
	public String getOrgdes() {
		return orgdes;
	}

	public void setOrgdes(String orgdes) {
		this.orgdes = orgdes;
	}

	@Column(name = "CALLNUM", length = 15)
	public String getCallnum() {
		return callnum;
	}

	public void setCallnum(String callnum) {
		this.callnum = callnum;
	}

	@Column(name = "PARENTCODE", length = 30)
	public String getParentcode() {
		return parentcode;
	}

	public void setParentcode(String parentcode) {
		this.parentcode = parentcode;
	}

	@Column(name = "PARENTNAME", length = 50)
	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	@Column(name = "BELONGCODE", length = 30)
	public String getBelongcode() {
		return belongcode;
	}

	public void setBelongcode(String belongcode) {
		this.belongcode = belongcode;
	}

	@Column(name = "BELONGNAME", length = 50)
	public String getBelongname() {
		return belongname;
	}

	public void setBelongname(String belongname) {
		this.belongname = belongname;
	}

	public Date getRuntime() {
		return runtime;
	}

	public void setRuntime(Date runtime) {
		this.runtime = runtime;
	}

	@Column(name = "MANAGEAREA", length = 50)
	public String getManagearea() {
		return managearea;
	}

	public void setManagearea(String managearea) {
		this.managearea = managearea;
	}

	@Column(name = "CATERINGTYPE", length = 20)
	public String getCateringtype() {
		return cateringtype;
	}

	public void setCateringtype(String cateringtype) {
		this.cateringtype = cateringtype;
	}

	@OneToMany(targetEntity=OrgStaff.class,cascade = CascadeType.REMOVE, fetch = FetchType.EAGER, mappedBy = "organize")
	public Set<OrgStaff> getOrgstaff() {
		return orgstaff;
	}

	public void setOrgstaff(Set<OrgStaff> orgstaff) {
		this.orgstaff = orgstaff;
	}

	@Column(name = "ORGTYPE", length = 30)
	public String getOrgtype() {
		return orgtype;
	}

	public void setOrgtype(String orgtype) {
		this.orgtype = orgtype;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}


}
