package com.orm;
// default package
// Generated 2015-5-21 22:24:34 by Hibernate Tools 3.2.2.GA

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "ORGSTAFF", schema = "ANYUE")
public class OrgStaff implements java.io.Serializable {

	private String staffcode;//店铺员工信息
	private String staffname;
	private String address;
	private String telephone;
	private String sex;
	private String identitycode;//身份证
	private byte[] healthcard;//健康证
	private Organize organize;
	
	public OrgStaff() {
	}

	public OrgStaff(String staffcode) {
		super();
		this.staffcode = staffcode;
	}

	public OrgStaff(String staffcode, String staffname, String address,
			String telephone, String sex, String identitycode,
			byte[] healthcard, Organize organize) {
		super();
		this.staffcode = staffcode;
		this.staffname = staffname;
		this.address = address;
		this.telephone = telephone;
		this.sex = sex;
		this.identitycode = identitycode;
		this.healthcard = healthcard;
		this.organize = organize;
	}

	@Id
	@Column(name = "STAFFCODE", unique = true, nullable = false, length = 20)
	public String getStaffcode() {
		return this.staffcode;
	}

	public void setStaffcode(String staffcode) {
		this.staffcode = staffcode;
	}

	@Column(name = "STAFFNAME", length = 20)
	public String getStaffname() {
		return staffname;
	}

	public void setStaffname(String staffname) {
		this.staffname = staffname;
	}

	@Column(name = "ADDRESS", length = 50)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "TELEPHONE", length = 15)
	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "SEX", length = 5)
	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "IDENTITYCODE", length = 20)
	public String getIdentitycode() {
		return identitycode;
	}

	public void setIdentitycode(String identitycode) {
		this.identitycode = identitycode;
	}

	@Lob
	@Basic(fetch = FetchType.LAZY)
	@Column(name = "HEALTHCARD", columnDefinition = "BLOB",nullable=true)
	public byte[] getHealthcard() {
		return healthcard;
	}

	public void setHealthcard(byte[] healthcard) {
		this.healthcard = healthcard;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ORGCODE")
	public Organize getOrganize() {
		return organize;
	}

	public void setOrganize(Organize organize) {
		this.organize = organize;
	}


}
