package com.orm;
// default package
// Generated 2015-5-21 22:24:34 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "OUTRUBBISH", schema = "ANYUE")
public class OutRubbish implements java.io.Serializable {

	private Integer id;
	private String orgcode;
	private String orgname;
	private String tittle;//简介
	private String outcontent;//废物类型或一些说明
	private Date outtime;//处理时间
	private Integer outnumber;//处理数量
	
	public OutRubbish() {
	}

	public OutRubbish(Integer id) {
		this.id = id;
	}


	public OutRubbish(Integer id, String orgcode, String orgname,
			String outcontent, Date outtime, Integer outnumber) {
		super();
		this.id = id;
		this.orgcode = orgcode;
		this.orgname = orgname;
		this.outcontent = outcontent;
		this.outtime = outtime;
		this.outnumber = outnumber;
	}

	@Id
	@SequenceGenerator(name="sequenceRubbish",sequenceName="SEQ")
	@GeneratedValue(generator="sequenceRubbish",strategy=GenerationType.SEQUENCE)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ORGCODE", length = 30)
	public String getOrgcode() {
		return orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	@Column(name = "ORGNAME", length = 30)
	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	@Column(name = "OUTCONTENT", length = 100)
	public String getOutcontent() {
		return outcontent;
	}

	public void setOutcontent(String outcontent) {
		this.outcontent = outcontent;
	}

	public Date getOuttime() {
		return outtime;
	}

	public void setOuttime(Date outtime) {
		this.outtime = outtime;
	}

	@Column(name = "OUTNUMBER", precision = 22, scale = 0)
	public Integer getOutnumber() {
		return outnumber;
	}

	public void setOutnumber(Integer outnumber) {
		this.outnumber = outnumber;
	}

	@Column(name = "TITTLE", length = 30)
	public String getTittle() {
		return tittle;
	}

	public void setTittle(String tittle) {
		this.tittle = tittle;
	}
	

}
