package com.orm;

// Generated 2015-4-1 10:16:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_ROLE", schema = "ANYUE")
public class SystemRole implements java.io.Serializable {

	private Integer id;
	private String rolename;
	private Integer rolemode;
	private Integer validflag;
	private Set systemmenus = new HashSet(0);
	private Set systemusers = new HashSet(0);

	public SystemRole() {
	}

	public SystemRole(Integer id) {
		this.id = id;
	}



	public SystemRole(Integer id, String rolename, Integer rolemode,
			Integer validflag, Set systemmenus) {
		super();
		this.id = id;
		this.rolename = rolename;
		this.rolemode = rolemode;
		this.validflag = validflag;
		this.systemmenus = systemmenus;
	}

	@Id
	@SequenceGenerator(name="sequenceMenu",sequenceName="SEQ")
	@GeneratedValue(generator="sequenceMenu",strategy=GenerationType.SEQUENCE)
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "ROLENAME", length = 30)
	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "ROLEMODE", length = 30)
	public Integer getRolemode() {
		return rolemode;
	}

	public void setRolemode(Integer rolemode) {
		this.rolemode = rolemode;
	}

	@Column(name = "VALIDFLAG", precision = 22, scale = 0)
	public Integer getValidflag() {
		return validflag;
	}

	public void setValidflag(Integer validflag) {
		this.validflag = validflag;
	}

	@ManyToMany(targetEntity=SystemMenu.class, cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
	@JoinTable(name = "ROLE_MENU", schema = "ANYUE", joinColumns = { @JoinColumn(name = "RID", nullable=false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "MID", nullable = false, updatable = false) })
	public Set getSystemmenus() {
		return systemmenus;
	}

	public void setSystemmenus(Set systemmenus) {
		this.systemmenus = systemmenus;
	}

	@OneToMany(targetEntity=SystemUser.class,cascade = CascadeType.REMOVE, fetch = FetchType.EAGER, mappedBy = "systemrole")
	public Set getSystemusers() {
		return systemusers;
	}

	public void setSystemusers(Set systemusers) {
		this.systemusers = systemusers;
	}

}
