package com.orm;

// Generated 2015-4-1 10:16:49 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_USER", schema = "ANYUE")
public class SystemUser implements java.io.Serializable {

	private Integer userid;
	private String usercode;
	private String username;
	private Integer userage;
	private String userkey;
	private String usertel;
	private String usersex;
	private String account;
	private String password;
	private String userrolename;
	private SystemRole systemrole;
	private String orgcode;
	private String orgname;
	private String email;

	public SystemUser() {
	}

	public SystemUser(Integer userid) {
		this.userid = userid;
	}

	public SystemUser(Integer userid, String username, String usercode, Integer userage,
			String userkey, String usertel, String usersex, String account,
			String password,SystemRole systemrole, String userrolename,String orgcode,String orgname,String email) {
		this.userid = userid;
		this.usercode=usercode;
		this.username = username;
		this.userage = userage;
		this.userkey = userkey;
		this.usertel = usertel;
		this.usersex = usersex;
		this.account = account;
		this.password = password;
		this.systemrole=systemrole;
		this.userrolename=userrolename;
		this.orgcode=orgcode;
		this.orgname=orgname;
		this.email=email;
	}

	@Id
	@SequenceGenerator(name="sequenceUser",sequenceName="SEQ")
	@GeneratedValue(generator="sequenceUser",strategy=GenerationType.SEQUENCE)
	@Column(name = "USERID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "USERNAME", length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "USERAGE", precision = 22, scale = 0)
	public Integer getUserage() {
		return this.userage;
	}

	public void setUserage(Integer userage) {
		this.userage = userage;
	}

	@Column(name = "USERKEY", length = 30)
	public String getUserkey() {
		return this.userkey;
	}

	public void setUserkey(String userkey) {
		this.userkey = userkey;
	}

	@Column(name = "USERTEL", length = 15)
	public String getUsertel() {
		return this.usertel;
	}

	public void setUsertel(String usertel) {
		this.usertel = usertel;
	}

	@Column(name = "USERSEX", length = 5)
	public String getUsersex() {
		return this.usersex;
	}

	public void setUsersex(String usersex) {
		this.usersex = usersex;
	}

	@Column(name = "ACCOUNT", unique = true, nullable = false, length = 20)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "PASSWORD", length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ROLE")
	public SystemRole getSystemrole() {
		return systemrole;
	}

	public void setSystemrole(SystemRole systemrole) {
		this.systemrole = systemrole;
	}

	@Column(name = "USERCODE", length = 20)
	public String getUsercode() {
		return usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}
	@Column(name = "USERROLENAME", length = 20)
	public String getUserrolename() {
		return userrolename;
	}

	public void setUserrolename(String userrolename) {
		this.userrolename = userrolename;
	}
	
	@Column(name = "ORGCODE", length = 20)
	public String getOrgcode() {
		return orgcode;
	}

	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	@Column(name = "ORGNAME", length = 20)
	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	@Column(name = "EMAIL", length = 20)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
