package com.orm;

// Generated 2015-4-1 10:16:49 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_MENU", schema = "ANYUE")
public class SystemMenu implements java.io.Serializable {

	private Integer id;
	private String menuname;
	private String englishname;
	private String text;


	private String menuurl;
	private String menutype;
	private Integer queryid;
	private Integer menulevel;
	private Integer parentid;
	private Set systemroles = new HashSet(0);
	public SystemMenu() {
	}

	public SystemMenu(Integer id) {
		this.id = id;
	}



	public SystemMenu(Integer id, String menuname, String englishname, String text, String menuurl,
			String menutype, Integer queryid, Integer menulevel, Integer parentid,Set systemroles) {
		super();
		this.id = id;
		this.menuname = menuname;
		this.englishname=englishname;
		this.text=text;
		this.menuurl = menuurl;
		this.menutype = menutype;
		this.queryid = queryid;
		this.menulevel=menulevel;
		this.parentid = parentid;
		this.systemroles=systemroles;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "MENUNAME", length = 100)
	public String getMenuname() {
		return menuname;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	@Column(name = "TEXT", length = 100)
	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}
	
	@Column(name = "MENUURL", length = 200)
	public String getMenuurl() {
		return menuurl;
	}

	public void setMenuurl(String menuurl) {
		this.menuurl = menuurl;
	}

	@Column(name = "MENUTYPE", length = 10)
	public String getMenutype() {
		return menutype;
	}

	public void setMenutype(String menutype) {
		this.menutype = menutype;
	}

	@Column(name = "QUERYID", precision = 22, scale = 0)
	public Integer getQueryid() {
		return queryid;
	}

	public void setQueryid(Integer queryid) {
		this.queryid = queryid;
	}

	@Column(name = "MENULEVEL", precision = 22, scale = 0)
	public Integer getMenulevel() {
		return menulevel;
	}

	public void setMenulevel(Integer menulevel) {
		this.menulevel = menulevel;
	}
	
	@Column(name = "PARENTID", precision = 22, scale = 0)
	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	@ManyToMany(targetEntity=SystemRole.class, cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
	@JoinTable(name = "ROLE_MENU", schema = "ANYUE", joinColumns = { @JoinColumn(name = "MID", nullable=false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "RID", nullable = false, updatable = false) })
	public Set getSystemroles() {
		return systemroles;
	}

	public void setSystemroles(Set systemroles) {
		this.systemroles = systemroles;
	}

	@Column(name = "ENGLISHNAME", length = 100)
	public String getEnglishname() {
		return englishname;
	}

	public void setEnglishname(String englishname) {
		this.englishname = englishname;
	}




}
